// src/routes/[ledgerid]/accounts/+page.svelte
<div class="space-y-4 p-4">
	{#each { length: 50 }, idx (idx)}
		<p class="container mx-auto">
			Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut voluptatibus laborum
			consequuntur impedit ipsa, rem unde repellendus ducimus cumque, fugiat id nihil quaerat. Neque
			fugit perferendis ipsa magnam tempore qui?
		</p>
	{/each}
</div>

// app/pages/[ledgerid]/accounts.vue
<template>
    <div class="space-y-4 p-4">
        {#each { length: 50 }, idx (idx)}
        <p class="container mx-auto">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut
            voluptatibus laborum consequuntur impedit ipsa, rem unde repellendus
            ducimus cumque, fugiat id nihil quaerat. Neque fugit perferendis
            ipsa magnam tempore qui?
        </p>
        {/each}
    </div>
</template>
