// app/pages/[ledgerid]/index.vue
<template>
<div class="p-4 flex flex-col gap-4">
	<div class="container mx-auto grid grid-cols-3 sm:flex gap-4">
		<h1 class="flex-1 text-2xl font-semibold">Summary</h1>

		<span>
			<p>BALANCE</p>
		</span>
		<span> <p>INCOME</p> </span>
		<span> <p>EXPENSE</p> </span>
	</div>
	<div class="container mx-auto md:(grid grid-cols-2) flex-1">
		<div>
			<h1>Income</h1>
		</div>
		<div>l</div>
	</div>
</div>
</template>

// src/routes/[ledgerid]/+page.svelte
<div class="p-4 flex flex-col gap-4">
	<div class="container mx-auto grid grid-cols-3 sm:flex gap-4">
		<h1 class="flex-1 text-2xl font-semibold">Summary</h1>

		<span>
			<p>BALANCE</p>
		</span>
		<span> <p>INCOME</p> </span>
		<span> <p>EXPENSE</p> </span>
	</div>
	<div class="container mx-auto md:(grid grid-cols-2) flex-1">
		<div>
			<h1>Income</h1>
		</div>
		<div>l</div>
	</div>
</div>
